// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedEquipCentral.Migrations
{
    [DbContext(typeof(MedEquipCentralDbContext))]
    [Migration("20240518184017_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedEquipCentral.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wound Care"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IV Therapy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "First Aid"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Diabetes Care"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Home Health Care"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mom & Baby Care"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mobility"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hearing Aids & Amplifiers"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Physical Therapy"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Scrubs"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Protection Wear"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Respiratory"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ostomy & Urology Supplies"
                        });
                });

            modelBuilder.Entity("MedEquipCentral.Models.JobFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobFunctions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Physician"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nurse Practitioner"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Registered Nurse"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Licensed Practical Nurse (LPN)"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Certified Nursing Assistant (CNA)"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Medical Assistant"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Surgeon"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Anesthesiologist"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pharmacist"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Physical Therapist"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Occupational Therapist"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Speech-Language Pathologist"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Dietitian/Nutritionist"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Respiratory Therapist"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Radiologic Technologist"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Medical Laboratory Technician"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Emergency Medical Technician (EMT)"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Paramedic"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Surgical Technologist"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Healthcare Administrator"
                        });
                });

            modelBuilder.Entity("MedEquipCentral.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CVV")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreditCardNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("ExpirationDate")
                        .HasColumnType("text");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("Zip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CVV = 123,
                            CloseDate = new DateTime(2024, 5, 16, 13, 40, 17, 562, DateTimeKind.Local).AddTicks(2733),
                            CreditCardNumber = 1234567890123456L,
                            ExpirationDate = "12/25",
                            IsClosed = true,
                            UserId = 1,
                            Zip = 12345
                        },
                        new
                        {
                            Id = 2,
                            CVV = 456,
                            CloseDate = new DateTime(2024, 5, 17, 13, 40, 17, 562, DateTimeKind.Local).AddTicks(2790),
                            CreditCardNumber = 9876543210987654L,
                            ExpirationDate = "03/27",
                            IsClosed = true,
                            UserId = 2,
                            Zip = 54321
                        });
                });

            modelBuilder.Entity("MedEquipCentral.Models.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("MedEquipCentral.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "High-quality adhesive bandages for minor cuts and scrapes.",
                            Image = "https://m.media-amazon.com/images/I/91D2FTeGRQL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Adhesive Bandages",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Comprehensive IV start kit with all necessary components.",
                            Image = "https://www.life-assist.com/Content/ProductImages/960x720/04_IT8052_01.jpg",
                            Name = "IV Start Kit",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Complete first aid kit for handling minor injuries.",
                            Image = "https://www.life-assist.com/Content/ProductImages/460x345/05_fj8000new.jpg",
                            Name = "First Aid Kit",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Accurate and easy-to-use blood glucose monitor for diabetes management.",
                            Image = "https://www.life-assist.com/Content/ProductImages/460x345/02_CHI708050_tstStrip.jpg",
                            Name = "Blood Glucose Monitor",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Essential health care kit for home use.",
                            Image = "https://i5.walmartimages.com/seo/Physical-Therapy-Home-Health-Aide-Kit-with-Home-Health-Call-Bag-for-Nurses-Home-Health-Aides-Physical-Therapy-Patient-Care_d9edc7e8-7ecb-4f7b-a7ef-3d7574236d7b.66cf77d8d12e2ad4af7201e2816d2236.jpeg?odnHeight=640&odnWidth=640&odnBg=FFFFFF",
                            Name = "Home Health Care Kit",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "Safe and accurate thermometer for babies.",
                            Image = "https://i5.walmartimages.com/seo/Metene-Forehead-Ear-Thermometer-Infrared-Thermometer-Baby-Kid-Adult-1s-Fast-Reading-2-Colors-Backlight-Fever-Alarm-20-Memories-Recall_5096cdf6-8a39-4237-bc22-e7d205b891e1.039d536705d4c3d17531552adb2fbed5.jpeg?odnHeight=640&odnWidth=640&odnBg=FFFFFF",
                            Name = "Baby Thermometer",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Description = "Durable and comfortable wheelchair for mobility assistance.",
                            Image = "https://m.media-amazon.com/images/I/81yOo8IZN7L._AC_SL1500_.jpg",
                            Name = "Wheelchair",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Description = "High-quality hearing aid for improved sound clarity.",
                            Image = "https://www.jabraenhance.com/cdn-cgi/image/width=1920,quality=90,format=auto/_next/static/media/pdp-gallery-champagne-pair-d.bd6c4aa6.jpg",
                            Name = "Hearing Aid",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            Description = "Set of resistance bands for physical therapy exercises.",
                            Image = "https://m.media-amazon.com/images/I/61QCIC8XbEL._SL1500_.jpg",
                            Name = "Physical Therapy Bands",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            Description = "Comfortable and durable medical scrubs.",
                            Image = "https://i5.walmartimages.com/seo/Dagacci-Medical-Uniform-Unisex-Scrubs-Set-Scrub-Top-and-Pants_ba9c0f34-3655-402a-a11a-622e774fe77c_1.dd2e4f217c097ccbba902dc77a0e6e66.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF",
                            Name = "Medical Scrubs",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 11,
                            Description = "Protective face shield for safety and hygiene.",
                            Image = "https://m.media-amazon.com/images/I/51CoS3sVsSL._SL1000_.jpg",
                            Name = "Face Shield",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 12,
                            Description = "Efficient nebulizer for respiratory therapy.",
                            Image = "https://omronhealthcare.com/wp-content/uploads/NEC801-FRONT-600x600-1.jpg",
                            Name = "Nebulizer",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 13,
                            Description = "High-quality ostomy bag for reliable use.",
                            Image = "https://m.media-amazon.com/images/I/71Xi70KyZUL._AC_SL1500_.jpg",
                            Name = "Ostomy Bag",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Hydrocolloid dressing for moist wound healing.",
                            Image = "https://m.media-amazon.com/images/I/51MfItI2NlL._SL1001_.jpg",
                            Name = "Hydrocolloid Dressing",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Complete IV drip set for intravenous therapy.",
                            Image = "https://cf1.bettymills.com/store/images/product/500/INDTCRTCBINF033G.JPG",
                            Name = "IV Drip Set",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "Compact emergency blanket for warmth and protection.",
                            Image = "https://img.kwcdn.com/product/fancy/5b446367-727e-45bb-91f4-1b01d60b29ab.jpg?imageView2/2/w/650/q/50/format/webp",
                            Name = "Emergency Blanket",
                            Price = 3.49m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "Easy-to-use insulin pen for diabetes management.",
                            Image = "https://www.adwdiabetes.com/images/autopen-delivery-system-blue.jpg",
                            Name = "Insulin Pen",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Description = "Portable oxygen concentrator for respiratory support.",
                            Image = "https://mainclinicsupply.com/cdn/shop/products/G5_300x300.jpg?v=1704317853",
                            Name = "Portable Oxygen Concentrator",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            Description = "High-definition baby monitor for parents' peace of mind.",
                            Image = "https://m.media-amazon.com/images/I/71q6DhYbHEL.__AC_SY300_SX300_QL70_FMwebp_.jpg",
                            Name = "Baby Monitor",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            Description = "Adjustable crutches for mobility assistance.",
                            Image = "https://m.media-amazon.com/images/I/416k+il1P6L._AC_SX569_.jpg",
                            Name = "Crutches",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 8,
                            Description = "Compact personal sound amplifier for enhanced hearing.",
                            Image = "https://example.com/images/products/sound_amplifier.jpg",
                            Name = "Personal Sound Amplifier",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 9,
                            Description = "Durable exercise ball for physical therapy and workouts.",
                            Image = "https://m.media-amazon.com/images/I/51T5RPDAS1L.__AC_SY300_SX300_QL70_FMwebp_.jpg",
                            Name = "Exercise Ball",
                            Price = 25.99m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 10,
                            Description = "Comfortable nurse uniform for professional use.",
                            Image = "https://m.media-amazon.com/images/I/51A9Xx2EVPS._AC_SX679_.jpg",
                            Name = "Nurse Uniform",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 11,
                            Description = "Disposable gowns for safety and hygiene in medical settings.",
                            Image = "https://m.media-amazon.com/images/I/41iMfJateLL._SY445_SX342_QL70_FMwebp_.jpg",
                            Name = "Disposable Gowns",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 12,
                            Description = "Reliable CPAP machine for sleep apnea treatment.",
                            Image = "https://m.media-amazon.com/images/I/41D0DqnhtxL._SY445_SX342_QL70_FMwebp_.jpg",
                            Name = "CPAP Machine",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 13,
                            Description = "High-quality urinary catheter for urological care.",
                            Image = "https://example.com/images/products/urinary_catheter.jpg",
                            Name = "Urinary Catheter",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            Description = "Sterile gauze pads for wound dressing.",
                            Image = "https://m.media-amazon.com/images/I/61a31ft455L.__AC_SY300_SX300_QL70_FMwebp_.jpg",
                            Name = "Sterile Gauze Pads",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Description = "IV extension set for flexible intravenous therapy.",
                            Image = "https://m.media-amazon.com/images/I/61dmwO5FNKL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "IV Extension Set",
                            Price = 8.49m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Description = "Portable CPR face shield for emergency resuscitation.",
                            Image = "https://m.media-amazon.com/images/I/61EgsjpRNZL._SX466_.jpg",
                            Name = "CPR Face Shield",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Description = "Lancet device for blood glucose testing.",
                            Image = "https://m.media-amazon.com/images/I/51ujEopXxnL._SY445_SX342_QL70_FMwebp_.jpg",
                            Name = "Lancet Device",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            Description = "Soothing burn gel for minor burns and scalds.",
                            Image = "https://m.media-amazon.com/images/I/51Ndif1TOCL._SX466_.jpg",
                            Name = "Burn Gel",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Description = "High-quality IV catheter for safe and efficient intravenous access.",
                            Image = "https://m.media-amazon.com/images/I/51BB53P2ZGL._SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "IV Catheter",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 5,
                            Description = "Convenient bedside commode for patients with mobility challenges.",
                            Image = "https://m.media-amazon.com/images/I/51jlhB25g1L.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Bedside Commode",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Description = "Sterile insulin pen needles for diabetes management.",
                            Image = "https://m.media-amazon.com/images/I/61rUPZsZzeS._SX466_.jpg",
                            Name = "Insulin Pen Needles",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 5,
                            Description = "Reliable blood pressure cuff for accurate readings.",
                            Image = "https://m.media-amazon.com/images/I/61o44znqdPL._AC_SX569_.jpg",
                            Name = "Blood Pressure Cuff",
                            Price = 22.00m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 6,
                            Description = "Gentle and moisturizing baby wipes for sensitive skin.",
                            Image = "https://m.media-amazon.com/images/I/41F1ayv1PbL._SY300_SX300_QL70_FMwebp_.jpg",
                            Name = "Baby Wipes",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 7,
                            Description = "Sturdy walker for enhanced mobility support.",
                            Image = "https://m.media-amazon.com/images/I/61qQ86d-jOL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Walker",
                            Price = 55.00m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 8,
                            Description = "Advanced digital hearing aid for better sound clarity.",
                            Image = "https://m.media-amazon.com/images/I/41QU5Ibd9CL._SY445_SX342_QL70_FMwebp_.jpg",
                            Name = "Digital Hearing Aid",
                            Price = 350.00m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 9,
                            Description = "High-density foam roller for muscle recovery and therapy.",
                            Image = "https://m.media-amazon.com/images/I/714oDUEbv+L._AC_SY300_SX300_.jpg",
                            Name = "Foam Roller",
                            Price = 18.99m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 10,
                            Description = "Comfortable and durable surgical scrubs.",
                            Image = "https://m.media-amazon.com/images/I/51vf7sWndyL._AC_SY679_.jpg",
                            Name = "Surgical Scrubs",
                            Price = 32.00m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 11,
                            Description = "Disposable protective gown for medical use.",
                            Image = "https://m.media-amazon.com/images/I/41tg-F8qEwL._SX342_SY445_QL70_FMwebp_.jpg",
                            Name = "Protective Gown",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 12,
                            Description = "Portable oxygen concentrator for respiratory support.",
                            Image = "https://m.media-amazon.com/images/I/71b8PsORslL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Portable Oxygen Concentrator",
                            Price = 450.00m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 7,
                            Description = "Portable folding cane for stability and support while walking.",
                            Image = "https://m.media-amazon.com/images/I/61TC-I8LR9L.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Folding Cane",
                            Price = 18.00m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 1,
                            Description = "Sterile wound dressing for effective healing.",
                            Image = "https://m.media-amazon.com/images/I/81nIh4kL9TL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Wound Dressing",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 2,
                            Description = "IV fluid bag for hydration and medication administration.",
                            Image = "https://m.media-amazon.com/images/I/514nbXKja2L.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "IV Fluid Bag",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Description = "Disposable blood glucose test strips for accurate glucose monitoring.",
                            Image = "https://m.media-amazon.com/images/I/41Ld08nwkdL._SY445_SX342_QL70_FMwebp_.jpg",
                            Name = "Blood Glucose Test Strips",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Description = "Sterile lancets for blood glucose testing.",
                            Image = "https://m.media-amazon.com/images/I/71P6oFj3KRL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Lancets",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Description = "Sturdy and adjustable portable shower chair.",
                            Image = "https://m.media-amazon.com/images/I/61pz5TDKuwL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Portable Shower Chair",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 6,
                            Description = "Gentle and effective nasal aspirator for infants.",
                            Image = "https://m.media-amazon.com/images/I/61IR8qxaxBL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Infant Nasal Aspirator",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 6,
                            Description = "Electric breast pump for efficient and comfortable milk expression.",
                            Image = "https://m.media-amazon.com/images/I/415zba+iXwL._SY300_SX300_.jpg",
                            Name = "Breast Pump",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 9,
                            Description = "Ergonomically designed orthopedic pillow for neck and spine support.",
                            Image = "https://m.media-amazon.com/images/I/61mdPtC0iIL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Orthopedic Pillow",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 1,
                            Description = "Stretchable compression bandage for wound management and support.",
                            Image = "https://m.media-amazon.com/images/I/614k6uqVbFL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Compression Bandage",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 2,
                            Description = "Complete IV infusion kit for home-based intravenous therapy.",
                            Image = "https://m.media-amazon.com/images/I/810m93ND8gL._AC_SX679_.jpg",
                            Name = "Home IV Infusion Kit",
                            Price = 34.99m
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 3,
                            Description = "Comprehensive first aid manual for emergency preparedness.",
                            Image = "https://m.media-amazon.com/images/I/81G4bfha0lL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Emergency First Aid Manual",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 4,
                            Description = "Portable cooling case for insulin storage during travel.",
                            Image = "https://m.media-amazon.com/images/I/71+qmT0A1JL._AC_SX569_.jpg",
                            Name = "Insulin Cooling Case",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 12,
                            Description = "Compact and portable nebulizer for on-the-go respiratory therapy.",
                            Image = "https://m.media-amazon.com/images/I/61tSm0np5HL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Portable Nebulizer",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 13,
                            Description = "Sterile urological drain bag for urinary collection and management.",
                            Image = "https://m.media-amazon.com/images/I/61wDA7XwFnS._AC_SY741_.jpg",
                            Name = "Urological Drain Bag",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 9,
                            Description = "Versatile knee support brace with adjustable straps for customized fit.",
                            Image = "https://m.media-amazon.com/images/I/61A4vopvL7S.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Adjustable Knee Support Brace",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 10,
                            Description = "Comfortable and breathable scrub caps for healthcare professionals.",
                            Image = "https://m.media-amazon.com/images/I/61-0J1+qCeL._AC_SX522_.jpg",
                            Name = "Reusable Scrub Caps",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 11,
                            Description = "Washable and reusable face masks for daily protection.",
                            Image = "https://m.media-amazon.com/images/I/41iS6HxvXnL._SY445_SX342_QL70_FMwebp_.jpg",
                            Name = "Reusable Face Masks",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 12,
                            Description = "Comfortable nasal mask for CPAP therapy in sleep apnea.",
                            Image = "https://m.media-amazon.com/images/I/4113F7qKOqL.__AC_SY300_SX300_QL70_FMwebp_.jpg",
                            Name = "CPAP Nasal Mask",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 13,
                            Description = "Adjustable straps for securing urinary leg bags comfortably.",
                            Image = "https://m.media-amazon.com/images/I/61F46vG4ECL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Urinary Leg Bag Straps",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 9,
                            Description = "Powerful muscle massage gun for deep tissue relaxation and recovery.",
                            Image = "https://m.media-amazon.com/images/I/71ILpYb00uL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Muscle Massage Gun",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 11,
                            Description = "Effective antibacterial hand sanitizer gel for hand hygiene.",
                            Image = "https://m.media-amazon.com/images/I/51COxBcVmML._SY445_SX342_QL70_FMwebp_.jpg",
                            Name = "Antibacterial Hand Sanitizer",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 5,
                            Description = "Portable and easy-to-use blood pressure monitor for home monitoring.",
                            Image = "https://m.media-amazon.com/images/I/714ytBdz2nL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Compact Blood Pressure Monitor",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 6,
                            Description = "Comfortable postpartum belly wrap for abdominal support and recovery.",
                            Image = "https://m.media-amazon.com/images/I/41eYV5uftZL._SY445_SX342_QL70_FMwebp_.jpg",
                            Name = "Postpartum Belly Wrap",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 3,
                            Description = "Fast and accurate digital thermometer for temperature measurement.",
                            Image = "https://m.media-amazon.com/images/I/51sO-p5+cQL._AC_SY300_SX300_.jpg",
                            Name = "Digital Thermometer",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 1,
                            Description = "Soft and breathable eye patch for post-operative or injury use.",
                            Image = "https://m.media-amazon.com/images/I/61VVJsEKlsL.__AC_SY300_SX300_QL70_FMwebp_.jpg",
                            Name = "Eye Patch",
                            Price = 3.49m
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 2,
                            Description = "Securement device for IV catheters to prevent dislodgement and movement.",
                            Image = "https://m.media-amazon.com/images/I/61f37xDXKrL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "IV Catheter Securement Device",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 11,
                            Description = "Disposable shoe covers for cleanliness and contamination control.",
                            Image = "https://m.media-amazon.com/images/I/71vWf-Mw5lL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Name = "Disposable Shoe Covers",
                            Price = 12.99m
                        });
                });

            modelBuilder.Entity("MedEquipCentral.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentReview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentReview = "Great product!",
                            DateCreated = new DateTime(2024, 5, 18, 18, 40, 17, 562, DateTimeKind.Utc).AddTicks(2823),
                            ProductId = 1,
                            Rating = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommentReview = "Excellent quality!",
                            DateCreated = new DateTime(2024, 5, 18, 18, 40, 17, 562, DateTimeKind.Utc).AddTicks(2825),
                            ProductId = 2,
                            Rating = 5,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("MedEquipCentral.Models.SimilarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SimilarProductId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SimilarProductId");

                    b.HasIndex("UserId");

                    b.ToTable("SimilarItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            SimilarProductId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            SimilarProductId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MedEquipCentral.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBizOwner")
                        .HasColumnType("boolean");

                    b.Property<int>("JobFunctionId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobFunctionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street",
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtUgBeWHwxqsREgJJ-2XJkV2S34fVpJz63b1AWjYHDgg&s",
                            IsAdmin = true,
                            IsBizOwner = true,
                            JobFunctionId = 3,
                            LastName = "Doe",
                            Uid = "JD123"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm Street",
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            Image = "https://headshots-inc.com/wp-content/uploads/2021/06/what-is-a-professional-headshot-example-header.jpg",
                            IsAdmin = false,
                            IsBizOwner = true,
                            JobFunctionId = 9,
                            LastName = "Smith",
                            Uid = "JS456"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak Street",
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPqh65K5r4_clBI27OhCX9_ULfL-dmy7kcVva_o-3-bg&s",
                            IsAdmin = false,
                            IsBizOwner = true,
                            JobFunctionId = 6,
                            LastName = "Johnson",
                            Uid = "AJ789"
                        });
                });

            modelBuilder.Entity("ProductUser", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("ProductsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ProductUser");
                });

            modelBuilder.Entity("MedEquipCentral.Models.Order", b =>
                {
                    b.HasOne("MedEquipCentral.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedEquipCentral.Models.OrderProduct", b =>
                {
                    b.HasOne("MedEquipCentral.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedEquipCentral.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MedEquipCentral.Models.Product", b =>
                {
                    b.HasOne("MedEquipCentral.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MedEquipCentral.Models.Review", b =>
                {
                    b.HasOne("MedEquipCentral.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedEquipCentral.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedEquipCentral.Models.SimilarItem", b =>
                {
                    b.HasOne("MedEquipCentral.Models.Product", "Product")
                        .WithMany("SimilarItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedEquipCentral.Models.Product", "SimilarProduct")
                        .WithMany()
                        .HasForeignKey("SimilarProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedEquipCentral.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SimilarProduct");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedEquipCentral.Models.User", b =>
                {
                    b.HasOne("MedEquipCentral.Models.JobFunction", "JobFunction")
                        .WithMany()
                        .HasForeignKey("JobFunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobFunction");
                });

            modelBuilder.Entity("ProductUser", b =>
                {
                    b.HasOne("MedEquipCentral.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedEquipCentral.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedEquipCentral.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MedEquipCentral.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("MedEquipCentral.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("Reviews");

                    b.Navigation("SimilarItems");
                });

            modelBuilder.Entity("MedEquipCentral.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
